server.port=8080

#Spring Data JPA

spring.datasource.url=jdbc:postgresql://dpg-d7k4bl7lk1mc738q6u3g-a:5432/platzi_play_db_casj
spring.datasource.username=macendales
spring.datasource.password=JW6BYLjxr15DKTwA8vKoFrGbysnAfKjr

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#LanChain4j
langchain4j.open-ai.chat-model.api-key=demo

