spring.profiles.active=dev

spring.application.name=platzi-play
server.servlet.context-path=/platzi-play/api

#Postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#LangChain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
